# Project 3

## Step 1

Please implement

* **HITS** and **PageRank** (Lecture 7, P37, random jumping probability, i.e., damping factor=0.15) and calculate authority, hub and PageRank values for the following 8 graphs
    * 6 graphs in project3dataset
    * 1 graphs from project1 transaction data (connect items in each row, bi-directed or directed)
* **SimRank** to calculate pair-wise similarity of nodes (choice any parameter C you like) , using
    * first 5 graphs of project3dataset.

project3dataset

* graph_1.txt: 6 nodes, 5 edges
* graph_2.txt: 5 nodes, 5 edges (a circle)
* graph_3.txt: 4 nodes, 6 edges
* graph_4.txt: 7 nodes, 18 edges (the example in Lecture3, p29)
* graph_5.txt:  469 nodes, 1102 edges
* graph_6.txt: 1228 nodes, 5220 edges

In [1]:
import numpy as np

In [2]:
NUM_OF_G1 = 6
NUM_OF_G2 = 5
NUM_OF_G3 = 4
NUM_OF_G4 = 7
NUM_OF_G5 = 469
NUM_OF_G6 = 1228
NUM_OF_G7 = 1228
NUM_OF_G8 = 7
NUM_OF_G9 = 5

In [3]:
graph1 = np.zeros((NUM_OF_G1, NUM_OF_G1), dtype=int)
with open('hw3dataset/graph_1.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph1[node1, node2] += 1

In [4]:
graph2 = np.zeros((NUM_OF_G2, NUM_OF_G2), dtype=int)
with open('hw3dataset/graph_2.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph2[node1, node2] += 1

In [5]:
graph3 = np.zeros((NUM_OF_G3, NUM_OF_G3), dtype=int)
with open('hw3dataset/graph_3.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph3[node1, node2] += 1

In [6]:
graph4 = np.zeros((NUM_OF_G4, NUM_OF_G4), dtype=int)
with open('hw3dataset/graph_4.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph4[node1, node2] += 1

In [7]:
graph5 = np.zeros((NUM_OF_G5, NUM_OF_G5), dtype=int)
with open('hw3dataset/graph_5.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph5[node1, node2] += 1

In [8]:
graph6 = np.zeros((NUM_OF_G6, NUM_OF_G6), dtype=int)
with open('hw3dataset/graph_6.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph6[node1, node2] += 1

In [9]:
# graph7 = np.zeros((NUM_OF_G7, NUM_OF_G7), dtype=int)
# with open('hw3dataset/graph_7.txt', 'r') as f:
#     for line in f.readlines():
#         node1, node2 = line.split(',')
#         node1, node2 = int(node1), int(node2)
#         node1, node2 = node1 - 1, node2 - 1
#         graph7[node1, node2] += 1

In [10]:
graph8 = np.zeros((NUM_OF_G8, NUM_OF_G8), dtype=int)
with open('hw3dataset/graph_8.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph8[node1, node2] += 1

In [11]:
graph9 = np.zeros((NUM_OF_G9, NUM_OF_G9), dtype=int)
with open('hw3dataset/graph_9.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph9[node1, node2] += 1

In [12]:
def HubsAuthorities(graph):
    row, col = graph.shape
    pre_ath = pre_hub = np.ones(row)
    epsilon = 1e-4
    epsilon_matrix = epsilon * np.ones(row)
    while True:
        ath = np.dot(pre_hub, graph)    # Sum of parents' hubs
        hub = np.dot(pre_ath, graph.T)  # Sum of children's authorities
        ath_nor = ath.max()
        hub_nor = hub.max()
        if ath_nor != 0:
            ath /= ath_nor
        if hub_nor != 0:
            hub /= hub_nor
        if (((abs(hub - pre_hub)) < epsilon_matrix).all()) and (((abs(ath - pre_ath)) < epsilon_matrix).all()):
            break
        pre_ath = ath
        pre_hub = hub
    return ath, hub

In [13]:
authority, hub = HubsAuthorities(graph1)
print(authority)
print(hub)

[0. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 0.]


In [14]:
authority, hub = HubsAuthorities(graph2)
print(authority)
print(hub)

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


In [15]:
authority, hub = HubsAuthorities(graph3)
print(authority)
print(hub)

[0.61805556 1.         1.         0.61805556]
[0.61805556 1.         1.         0.61805556]


In [16]:
authority, hub = HubsAuthorities(graph4)
print(authority)
print(hub)

[0.6925528  0.88327064 0.99702723 0.69595035 1.         0.27848743
 0.41746292]
[1.         0.17340843 0.39457369 0.72120808 0.66705026 0.4238019
 0.25039347]


In [17]:
authority, hub = HubsAuthorities(graph5)
print(authority)
print(hub)

[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 3.61718618e-11 1.95876049e-06 4.95154648e-10
 7.87660980e-16 7.87660980e-16 4.95154648e-10 1.95876049e-06
 7.87660980e-16 7.87660980e-16 1.95876049e-06 1.53362226e-02
 2.03973561e-09 5.14320044e-02 1.87068776e-10 6.43244760e-08
 7.58892911e-07 8.98713569e-07 6.43244760e-08 1.09659824e-06
 3.51267113e-02 3.88813097e-11 3.59524842e-11 2.03973561e-09
 2.03973561e-09 3.07680070e-18 1.15962203e-10 1.99247626e-10
 3.07680070e-18 7.88550368e-17 1.75326442e-06 1.38429519e-02
 2.56979163e-02 2.73242412e-02 6.43244760e-08 6.64909479e-06
 2.03973561e-09 6.43244760e-08 5.78053226e-06 8.86593471e-06
 2.03973561e-09 2.01325880e-05 2.78462952e-11 3.19553947e-02
 1.53362226e-02 5.24734647e-02 1.53362226e-02 1.99247626e-10
 2.01641211e-13 1.38429519e-02 8.91315956e-02 2.00969204e-02
 3.94660474e-10 3.57606369e-02 2.04121245e-10 1.42464660e-05
 1.00000000e+00 3.94660474e-10 3.26101432e-10 2.03973561e-09
 5.15265278e-12 2.016412

In [18]:
authority, hub = HubsAuthorities(graph6)
print(authority)
print(hub)

[0.00000000e+00 2.96854728e-02 1.70241589e-28 ... 4.95592491e-03
 4.49038543e-01 3.87871129e-28]
[0.16691988 0.         0.         ... 0.         0.60278356 0.        ]


In [19]:
# authority, hub = HubsAuthorities(graph)
# print(authority)
# print(hub)

In [20]:
authority, hub = HubsAuthorities(graph8)
print(authority)
print(hub)

[0.6925528  0.88327064 0.99702723 0.69595035 1.         0.27848743
 0.41746292]
[1.         0.17340843 0.39457369 0.72120808 0.66705026 0.4238019
 0.25039347]


In [21]:
def PageRank_m(graph):
    row, col = graph.shape
    one = np.ones(row)
    pre_r = z = one / row
    epsilon = 1
    # epsilon_matrix = epsilon * np.ones(row)
    while True:
        r = np.dot(pre_r, graph)
        diff = pre_r - r
        r = r + diff * z
        delta = np.dot(abs(r - pre_r), one)
        if delta < epsilon:
            break
        pre_r = r
    return r    

In [22]:
def PageRank(graph, d=0.15, epsilon = 0.0001):
    row, col = graph.shape
    L = []
    p = []
    c = []
    for i in range(0, row):
        L.append(np.nonzero(graph[:, i])[0])   # get node i's parents
        children = np.nonzero(graph[i, :])[0]  # get node i's children
        p.append(L[i].shape[0])                # number of node i's parents
        c.append(children.shape[0])            # number of node i's children
    c = np.array(c)
    delta = d / row                            # d: damping factor
    x = np.ones(row) / row
    z = np.zeros(row)
    while max(abs(x - z)) > epsilon:
        z = x
        x = np.zeros(row)
        for j in range(0, row):
            if p[j] != 0:
                x[j] = np.sum(z[L[j]] / c[L[j]])  # 
        x = delta + (1 - d) * x
    return x 

In [23]:
PageRank(graph1)

array([0.025     , 0.04625   , 0.0643125 , 0.07966562, 0.09271578,
       0.10380841])

In [24]:
PageRank(graph2)

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [25]:
PageRank(graph3)

array([0.17545293, 0.32454707, 0.32454707, 0.17545293])

In [26]:
PageRank(graph4)

array([0.28030889, 0.15875323, 0.1388805 , 0.10822254, 0.18418373,
       0.06057982, 0.06907129])

In [27]:
PageRank(graph5)

array([0.00031983, 0.00031983, 0.00031983, 0.00031983, 0.00031983,
       0.00036514, 0.00034701, 0.00035867, 0.00038779, 0.00038779,
       0.00035867, 0.00034701, 0.00038779, 0.00038779, 0.00034701,
       0.00033171, 0.00033278, 0.00038277, 0.00039259, 0.00033151,
       0.00078922, 0.0007675 , 0.00033151, 0.00087509, 0.00035753,
       0.00036417, 0.00036955, 0.00033278, 0.00033278, 0.00048043,
       0.0003902 , 0.00034295, 0.00049404, 0.00044994, 0.00052542,
       0.00038406, 0.00035096, 0.00032963, 0.00033151, 0.00084556,
       0.00033278, 0.00033151, 0.000791  , 0.0009688 , 0.00033278,
       0.00052681, 0.00044927, 0.00037598, 0.00033171, 0.00036076,
       0.00033171, 0.00034295, 0.00035852, 0.00038406, 0.00043226,
       0.0003354 , 0.00034056, 0.00036951, 0.00033636, 0.00047779,
       0.00289161, 0.00034056, 0.0005131 , 0.00033278, 0.00044731,
       0.00035909, 0.00033151, 0.00034176, 0.00034558, 0.0005206 ,
       0.00036527, 0.00044994, 0.00034194, 0.00035852, 0.00032

In [28]:
PageRank(graph6)

array([0.00012215, 0.00013003, 0.00012692, ..., 0.00013081, 0.00039077,
       0.00013074])

In [29]:
PageRank(graph8, d=0)

array([0.30350624, 0.16613374, 0.14057886, 0.10543791, 0.17890534,
       0.04472903, 0.06070888])

In [30]:
def SimRank(graph, C=0.6, K=5):
    '''
    Args:
        gragh: adjacency matrix
        C: dacay factor
        K: num of iteration
    Return:
        SimRank
    '''
    row, col = graph.shape
    s = np.identity(row)     # Init SimRank
    parents = []             # Parents of each node
    p = []                   # Num of parents of each node
    for i in range(row):
        tmp = np.nonzero(graph[:, i])[0]
        parents.append(tmp)
        p.append(tmp.shape[0])
    
    for k in range(K):
        new_s = np.zeros((row, col))          # New SimRank for new iteration
        for a in range(row):
            for b in range(col):
                if a == b:                    # s(a, a) = 1
                    new_s[a, b] = 1
                    continue
                if p[a] == 0 or p[b] == 0:    # Either a or b has no parent, s(a, b) = 0
                    new_s[a, b] = 0
                    continue
                tmp = 0
                for i in range(p[a]):
                    for j in range(p[b]):
                        tmp += s[parents[a][i], parents[b][j]]
                new_s[a, b] = C / (p[a] * p[b]) * tmp
        s = new_s                             # Overwrite s
    return s

In [31]:
SimRank(graph1)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
SimRank(graph2)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
SimRank(graph3)

array([[1.     , 0.     , 0.42753, 0.     ],
       [0.     , 1.     , 0.     , 0.42753],
       [0.42753, 0.     , 1.     , 0.     ],
       [0.     , 0.42753, 0.     , 1.     ]])

In [34]:
SimRank(graph4)

array([[1.        , 0.15988661, 0.15116696, 0.15890875, 0.14110127,
        0.22046254, 0.09735495],
       [0.15988661, 1.        , 0.21135951, 0.17659008, 0.20921613,
        0.09362145, 0.2595587 ],
       [0.15116696, 0.21135951, 1.        , 0.25684477, 0.19281811,
        0.25615471, 0.25753483],
       [0.15890875, 0.17659008, 0.25684477, 1.        , 0.15229394,
        0.34048543, 0.34048543],
       [0.14110127, 0.20921613, 0.19281811, 0.15229394, 1.        ,
        0.08586267, 0.21872522],
       [0.22046254, 0.09362145, 0.25615471, 0.34048543, 0.08586267,
        1.        , 0.08097086],
       [0.09735495, 0.2595587 , 0.25753483, 0.34048543, 0.21872522,
        0.08097086, 1.        ]])

In [35]:
SimRank(graph5)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
SimRank(graph9, K=1)

array([[1. , 0. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 1. , 0. , 0.3],
       [0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0.3, 0. , 1. ]])

## Step 2

Find a way (e.g., add/delete some links) to increase hub, authority, and PageRank of Node 1 in first 3 graphs respectively.

## Step 3

Please describe and analysis your results for each algorithm in each graph.