# Project 3

Please implement
* HITS and PageRank (Lecture 7, P37, random jumping probability, i.e., damping factor=0.15) and calculate authority, hub and PageRank values for the following 8 graphs
    * 6 graphs in project3dataset
    * 1 graphs from project1 transaction data (connect items in each row, bi-directed or directed)
* SimRank to calculate pair-wise similarity of nodes (choice any parameter C you like) , using
    * first 5 graphs of project3dataset.

project3dataset
* graph_1.txt: 6 nodes, 5 edges
* graph_2.txt: 5 nodes, 5 edges (a circle)
* graph_3.txt: 4 nodes, 6 edges
* graph_4.txt: 7 nodes, 18 edges (the example in Lecture3, p29)
* graph_5.txt:  469 nodes, 1102 edges
* graph_6.txt: 1228 nodes, 5220 edges

In [1]:
import numpy as np

In [2]:
NUM_OF_G1 = 6
NUM_OF_G2 = 5
NUM_OF_G3 = 4
NUM_OF_G4 = 7
NUM_OF_G5 = 469
NUM_OF_G6 = 1228
NUM_OF_G7 = 1228
NUM_OF_G8 = 7

In [3]:
graph1 = np.zeros((NUM_OF_G1, NUM_OF_G1), dtype=int)
with open('hw3dataset/graph_1.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph1[node1, node2] += 1

In [4]:
graph2 = np.zeros((NUM_OF_G2, NUM_OF_G2), dtype=int)
with open('hw3dataset/graph_2.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph2[node1, node2] += 1

In [5]:
graph3 = np.zeros((NUM_OF_G3, NUM_OF_G3), dtype=int)
with open('hw3dataset/graph_3.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph3[node1, node2] += 1

In [6]:
graph4 = np.zeros((NUM_OF_G4, NUM_OF_G4), dtype=int)
with open('hw3dataset/graph_4.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph4[node1, node2] += 1

In [7]:
graph5 = np.zeros((NUM_OF_G5, NUM_OF_G5), dtype=int)
with open('hw3dataset/graph_5.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph5[node1, node2] += 1

In [8]:
graph6 = np.zeros((NUM_OF_G6, NUM_OF_G6), dtype=int)
with open('hw3dataset/graph_6.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph6[node1, node2] += 1

In [9]:
# graph7 = np.zeros((NUM_OF_G7, NUM_OF_G7), dtype=int)
# with open('hw3dataset/graph_7.txt', 'r') as f:
#     for line in f.readlines():
#         node1, node2 = line.split(',')
#         node1, node2 = int(node1), int(node2)
#         node1, node2 = node1 - 1, node2 - 1
#         graph7[node1, node2] += 1

In [10]:
graph8 = np.zeros((NUM_OF_G8, NUM_OF_G8), dtype=int)
with open('hw3dataset/graph_8.txt', 'r') as f:
    for line in f.readlines():
        node1, node2 = line.split(',')
        node1, node2 = int(node1), int(node2)
        node1, node2 = node1 - 1, node2 - 1
        graph8[node1, node2] += 1

In [11]:
def HubsAuthorities(graph):
    row, col = graph.shape
    pre_ath = pre_hub = np.ones(row)
    epsilon = 1e-4
    epsilon_matrix = epsilon * np.ones(row)
    while True:
        ath = np.dot(pre_hub, graph)    # Sum of parents' hubs
        hub = np.dot(pre_ath, graph.T)  # Sum of children's authorities
        ath_nor = ath.max()
        hub_nor = hub.max()
        if ath_nor != 0:
            ath /= ath_nor
        if hub_nor != 0:
            hub /= hub_nor
        if (((abs(hub - pre_hub)) < epsilon_matrix).all()) and (((abs(ath - pre_ath)) < epsilon_matrix).all()):
            break
        pre_ath = ath
        pre_hub = hub
    return ath, hub

In [12]:
authority, hub = HubsAuthorities(graph8)
print(authority)
print(hub)

[0.6925528  0.88327064 0.99702723 0.69595035 1.         0.27848743
 0.41746292]
[1.         0.17340843 0.39457369 0.72120808 0.66705026 0.4238019
 0.25039347]


In [13]:
def PageRank_m(graph):
    row, col = graph.shape
    one = np.ones(row)
    pre_r = z = one / row
    epsilon = 1
    # epsilon_matrix = epsilon * np.ones(row)
    while True:
        r = np.dot(pre_r, graph)
        diff = pre_r - r
        r = r + diff * z
        delta = np.dot(abs(r - pre_r), one)
        if delta < epsilon:
            break
        pre_r = r
    return r    

In [14]:
def PageRank_matlab(graph):
    row, col = graph.shape
    L = []
    c = []
    for i in range(0, row):
        L.append(np.nonzero(graph[:, i])[0])  # 
        c.append(L[i].shape[0])
    print(L)
    print(c)
    d = 0.15                         # damping factor
    delta = d / row
    x = np.ones(row) / row
    z = np.zeros(row)
    epsilon = 0.0001
    while max(abs(x - z)) > epsilon:
        z = x
        x = np.zeros(row)
        for j in range(0, row):
            if c[j] == 0:
                x = x + z[j] / row   # 轉移到任意一個網頁
            else:
                x[L[j]] = x[L[j]] + z[j] / c[j]  # 將上次的pagerank值平攤給所有指向的網頁
        x = delta + (1 - d) * x
    return x    

In [15]:
def PageRank_matlabv2(graph):
    row, col = graph.shape
    L = []
    c = []
    for i in range(0, row):
        L.append(np.nonzero(graph[:, i])[0])  # node i's parents
        c.append(L[i].shape[0])               # number of parents
    d = 0.15                         # damping factor
    delta = d / row
    x = np.ones(row) / row
    z = np.zeros(row)
    epsilon = 0.0001
    while max(abs(x - z)) > epsilon:
        z = x
        x = np.zeros(row)
        for j in range(0, row):
            # if c[j] == 0:
            #     x = x + z[j] / row   # 轉移到任意一個網頁
            # else:
            if c[j] != 0:
                x[L[j]] = x[L[j]] + z[j] / c[j]  # 將上次的pagerank值平攤給所有指向的網頁
        # x = delta + (1 - d) * x
    return x 

In [16]:
def PageRank_what(graph):
    row, col = graph.shape
    L = []
    c = []
    for i in range(0, row):
        L.append(np.nonzero(graph[:, i])[0])
        c.append(L[i].shape[0])
    # d = 0.15                         # damping factor
    # delta = d / row
    x = np.ones(row) / row
    z = np.zeros(row)
    epsilon = 0.0001
    while max(abs(x - z)) > epsilon:
        z = x
        x = np.zeros(row)
        for j in range(0, row):
            if c[j] != 0:
                # print(x[L[j]])
                # print(z[j])
                x[j] = np.sum(x[L[j]] + z[j] / c[j])  # 將上次的pagerank值平攤給所有指向的網頁
                # break
        # x = delta + (1 - d) * x
    return x    

In [17]:
def PageRank(graph, d=0.15, epsilon = 0.0001):
    row, col = graph.shape
    L = []
    p = []
    c = []
    for i in range(0, row):
        L.append(np.nonzero(graph[:, i])[0])   # get node i's parents
        children = np.nonzero(graph[i, :])[0]  # get node i's children
        p.append(children.shape[0])            # number of node i's parents
        c.append(children.shape[0])            # number of node i's children
    c = np.array(c)
    delta = d / row                            # d: damping factor
    x = np.ones(row) / row
    z = np.zeros(row)
    while max(abs(x - z)) > epsilon:
        z = x
        x = np.zeros(row)
        for j in range(0, row):
            if p[j] != 0:
                x[j] = np.sum(z[L[j]] / c[L[j]])  # 
        x = delta + (1 - d) * x
    return x 

In [18]:
PageRank(graph1)

array([0.025     , 0.04625   , 0.0643125 , 0.07966562, 0.09271578,
       0.025     ])

In [19]:
PageRank(graph2)

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [20]:
PageRank(graph3)

array([0.17545293, 0.32454707, 0.32454707, 0.17545293])

In [21]:
PageRank(graph4)

array([0.28030889, 0.15875323, 0.1388805 , 0.10822254, 0.18418373,
       0.06057982, 0.06907129])

In [22]:
PageRank(graph5)

array([0.00031983, 0.00031983, 0.00031983, 0.00031983, 0.00031983,
       0.00036514, 0.00034701, 0.00031983, 0.00031983, 0.00031983,
       0.00035867, 0.00034701, 0.00038779, 0.00031983, 0.00031983,
       0.00031983, 0.00031983, 0.00031983, 0.00031983, 0.00031983,
       0.00031983, 0.00031983, 0.00031983, 0.00031983, 0.00031983,
       0.00031983, 0.00036955, 0.00031983, 0.00031983, 0.00031983,
       0.00039025, 0.00031983, 0.00031983, 0.00044994, 0.00031983,
       0.00031983, 0.00035096, 0.00032963, 0.00031983, 0.00031983,
       0.00031983, 0.00031983, 0.00080821, 0.00031983, 0.00031983,
       0.00031983, 0.00045036, 0.00031983, 0.00031983, 0.00031983,
       0.00031983, 0.00031983, 0.00031983, 0.00031983, 0.00031983,
       0.0003354 , 0.00031983, 0.00036952, 0.00031983, 0.0004779 ,
       0.00031983, 0.00031983, 0.00031983, 0.00031983, 0.00031983,
       0.00031983, 0.00031983, 0.00031983, 0.00031983, 0.00052627,
       0.00031983, 0.00044994, 0.00031983, 0.00031983, 0.00031

In [23]:
PageRank(graph6)

array([0.00012215, 0.00012215, 0.00012215, ..., 0.00012215, 0.00039077,
       0.00012215])

In [24]:
PageRank(graph8, d=0)

array([0.30350624, 0.16613374, 0.14057886, 0.10543791, 0.17890534,
       0.04472903, 0.06070888])

Find a way (e.g., add/delete some links) to increase hub, authority, and PageRank of Node 1 in first 3 graphs respectively.